/* ProtoSpace Analyzer — what each descriptor looks for, what it counts, and how it is scored.
   Written to match js/analyzer.js and js/rubric.js exactly: the counts and thresholds here are the ones the code uses. */

/* How the model is read before any descriptor is rated — the shared vocabulary. */
export const READING = [
  ['Face cells', 'The frame is looked at from the front, 1 m per cell. Each cell is classed by how deep its first cube sits: <b>mass</b> when the first cube is within 8 m of the front (the building\'s face), <b>recess</b> when it is 9 m or deeper, <b>see-through</b> when there is no cube at all.'],
  ['Envelope, floors, modules', 'The envelope is the extent of everything built. Floors are 3 m tall, counted from the lowest built row. Modules are the 9 × 3 m cells of a grid fitted over the envelope where the full-or-empty reading is clearest; a module is <b>occupied</b> when at least half of it is mass.'],
  ['Gathering pocket', 'A connected patch of recess of at least 12 m² inside the envelope — a sheltered place off the face where people could gather.'],
  ['Street and bridge', 'A run of recess along one row, with mass under at least half of its length (a floor edge). 5 m or longer it is a <b>street</b>; 2–4 m it is a <b>bridge</b>.'],
  ['Opening', 'A see-through void of at least 2 m² with building all around it — a hole you look straight through, not the sky at the edge.'],
  ['Territory', 'A connected run of mass within one 3 m floor: a unit people could occupy. Its area is its length × 9 m of assumed depth, at 10 m² per person.'],
  ['Spatial types', 'Every cell is one of: work (mass), gathering pocket, street, bridge, terrace (recess with mass below and nothing above), covered recess, see-through opening.'],
  ['Sightline', 'From the middle of an occupied module, a straight look along the floor or up / down across 3–24 m of void that ends on mass — another territory or another level.'],
];

/* Per descriptor: the plain question, the architectural idea, exactly what is counted, how the pieces are scored,
   what raises it, what lowers it, and what it cannot tell. `score` lines follow the order of the measured terms. */
export const GUIDE = {
  'Modular': {
    ask: 'Is it built from repeated 9 × 3 m units you can clearly read, each one either full or empty?',
    looks: 'A modular building reads as an assembly of repeated units of the same size. The eye should find the unit, see it repeated, and see each unit as either there or not — half-filled units blur the system.',
    counts: ['The 9 × 3 m module grid, fitted over the envelope where the full / empty reading is clearest.', 'For every module cell, the share of its 27 m² that is mass. A cell at least 70 % mass is <b>full</b>; at most 30 % is <b>empty</b>; the rest are half-filled and count against clarity.', 'How much of all the face mass sits inside full module cells.'],
    score: ['Mass inside complete modules · 65 %: the share of the face mass that sits in full module cells (100 % when every bit of mass belongs to a full cell).', 'Module cells that read clearly · 35 %: full + empty cells over all module cells (100 % when no cell is half-filled).'],
    raise: 'Fill a module cell completely or leave it empty; alternate full and empty cells so the face reads as an assembly rather than one block.',
    lower: 'Masses that cut across the 9 × 3 m grid, half-filled cells, one continuous slab.',
    cannot: 'It measures visual repetition on the face; it says nothing about construction modules or structure.',
  },
  'Fragmented': {
    ask: 'Does the face break into several separate bodies, while most of the mass still holds together?',
    looks: 'A fragmented form reads as distinct pieces or territories rather than one continuous body. The score rewards several readable bodies and mass that is not all joined into one; whether the separation is intentional is a judgment for the review.',
    counts: ['Bodies of face mass: connected patches of mass cells of at least 6 m² (<b>territories</b>).', 'The largest body, and the share of all face mass joined into it (<b>cohesion</b>).'],
    score: ['Identifiable territories · 50 %: the number of bodies over 5 (five or more earns full marks).', 'Mass outside the largest body · 50 %: 1 − cohesion — 0 % when all the mass is one body, rising as it separates into others.'],
    raise: 'Cut recesses and openings that split the mass into several bodies of at least 6 m².',
    lower: 'One connected slab: few bodies, and all the mass joined into one. Pieces under 6 m² are crumbs and do not count as bodies.',
    cannot: 'Separation is read on the face only; pieces that look separate may join behind it, and more fragmentation is not automatically better.',
  },
  'Interlocking': {
    ask: 'Do neighbouring units overlap only partly or step in depth — across floors as much as side by side?',
    looks: 'Interlocking parts engage each other: a unit overlaps the one beside or below it only partly, or steps forward or back from it, so the pieces hook together instead of stacking in neat rows.',
    counts: ['Every pair of occupied modules that touch: <b>side by side</b> (same floor) and <b>floor to floor</b>.', 'For each pair, the overlap of their mass profiles (which metres of the shared edge carry mass on both sides) and whether their average depth differs by half the depth range (<b>a step in depth</b>).', 'A joint <b>interlocks</b> when the overlap is partial (side by side: between 0 and 100 %; floor to floor: 20–80 %) or the pair steps in depth.'],
    score: ['Connections between modules · 25 %: side-by-side + floor-to-floor pairs over 21.', 'Interlocking joints · 50 %: joints that overlap partly or step in depth, over 9.', 'Balance horizontal / vertical · 25 %: 1 − |side-by-side − floor-to-floor| / total (100 % when there are as many of each).'],
    raise: 'Shift modules half a bay, or a few metres in depth, against their neighbours; let modules step over the ones below.',
    lower: 'Modules stacked exactly on top of each other, or lined up only side by side.',
    cannot: 'Contact and depth steps are visual proxies: they do not confirm physical joints, doors between units or load paths.',
  },
  'Porous': {
    ask: 'Is about half to two-thirds of the envelope void, with holes you can see right through?',
    looks: 'A porous body is still a body — one mass — but shot through with openings and deep recesses, so light, views and people pass through it. Too dense and it is a wall; too open and there is no body left.',
    counts: ['Inside the envelope: cells that are <b>see-through</b> and cells that are <b>deep recess</b> (first cube 9 m or deeper). Together they are the void share.', '<b>Openings</b>: see-through voids of at least 2 m² with building all around them.'],
    score: ['Void within the envelope · 60 %: full marks between 50 % and 66 % void; nothing at 15 % or below and at 90 % or above, rising and falling in between.', 'Openings you see right through · 40 %: the number of enclosed openings over 2 (two or more earns full marks).'],
    raise: 'Carve voids and deep recesses until roughly half to two-thirds of the envelope is open; cut holes that pass right through, surrounded by mass.',
    lower: 'A dense face (little void) or a skeleton so open it no longer reads as a body; voids only at the edges, never through the middle.',
    cannot: 'Void is read from the front; it does not know whether an opening actually connects spaces behind the face.',
  },
  'Clustered': {
    ask: 'Do the units gather into 2–6 groups of 3–10 modules, rather than one block or loners?',
    looks: 'Clustered units form identifiable groups with readable boundaries — small neighbourhoods of modules — not one undifferentiated block, and not isolated singles.',
    counts: ['Occupied modules that touch (side by side or floor to floor) are joined into <b>clusters</b>.', 'The number of clusters, their sizes, and the share of occupied modules that sit in clusters of 3 to 10.'],
    score: ['Clusters of joined modules · 25 %: full marks between 2 and 6 clusters; nothing at 0 or at 14 or more.', 'Modules per cluster · 30 %: full marks for an average of 3 to 10; nothing at 1 or at 20 or more.', 'Modules in 3–10 module clusters · 45 %: the share of occupied modules that belong to such a group.'],
    raise: 'Separate the mass into a few groups with shared voids between them; gather loners into groups of 3 to 10.',
    lower: 'One big cluster (a block), or many singles and pairs.',
    cannot: 'Groups are read from adjacency on the face; it does not know which units actually share a function.',
  },
  'Decentralized': {
    ask: 'Are gathering pockets spread through the building — close to every unit and on most floors?',
    looks: 'In a decentralised building the shared spaces are distributed, not concentrated at one entrance hall: every unit has a gathering place nearby, on its own level or the next.',
    counts: ['<b>Gathering pockets</b>: connected recesses of at least 12 m² inside the envelope.', 'From the centre of every occupied module, the straight-line distance to the nearest pocket cell.', 'How many of the floors have a pocket.'],
    score: ['Distance to the nearest gathering pocket · 45 %: the average over occupied modules — full marks at 2.4 m or less, nothing at 6.1 m or more.', 'Gathering pockets · 30 %: the square root of (pockets over 5).', 'Floors with a pocket · 25 %: the square root of (floors with a pocket over all floors).'],
    raise: 'Carve pockets of at least 12 m² into the face near the modules at the edges, and on more floors.',
    lower: 'No recess of 12 m², or all the pockets on one level or in one corner.',
    cannot: 'A pocket is a recess, not a verified room; distance is measured on the face, not along a route.',
  },
  'Networked': {
    ask: 'Does every unit have several ways out — neighbours, streets and bridges?',
    looks: 'A networked building offers route choices: from any unit you can go several ways, through neighbouring units, along streets or over bridges, rather than down one corridor.',
    counts: ['For every occupied module, its potential links: occupied <b>neighbours</b> (side by side and floor to floor) plus every <b>street</b> or <b>bridge</b> that touches it.', 'The share of modules with three or more links.'],
    score: ['Potential links per module · 60 %: the average number of links over 3.6.', 'Modules with three or more · 40 %: the share of occupied modules with at least three links.'],
    raise: 'Leave floor-level recesses of 5 m or more running along the face (streets) and shorter ones between units (bridges) on more floors; give the edge modules a second and third link.',
    lower: 'No streets at all, modules in a single row, dead ends.',
    cannot: 'Links are geometric adjacencies; whether a route is really walkable (doors, levels, stairs) is not verified.',
  },
  'Layered': {
    ask: 'Do work, streets, pockets and terraces overlap in and around each unit, and stack over one another?',
    looks: 'A layered building overlaps different kinds of space — work, circulation, gathering, terraces, openings — within and around every unit and over its height, instead of zoning them apart.',
    counts: ['Every cell\'s <b>spatial type</b>: work, gathering pocket, street, bridge, terrace, covered recess, see-through opening.', 'For every occupied module, how many different types sit inside it or directly beside it (one cell around).', 'For every 1 m column of the plan, how many types are stacked over its height.'],
    score: ['Spatial types in or beside each module · 55 %: the average number of types over 4.', 'Columns mixing three or more spatial types · 45 %: the share of plan columns that stack at least three types.'],
    raise: 'Bring streets and pockets right up against the work units; put terraces over streets and pockets under work so types stack vertically.',
    lower: 'Work on one side, circulation on another, gathering in one zone — each type in its own place.',
    cannot: 'Types are read from depth on the face; a "terrace" is a recess with nothing above it, not a verified usable floor.',
  },
  'Intimate': {
    ask: 'Are the territories the size of a room for 4–12 people — not halls, not cells?',
    looks: 'Intimate space is human-scaled: territories a small group can own, with enclosure and a sense of proximity. A hall for forty is not intimate; a cell for one is not a group.',
    counts: ['<b>Territories</b>: connected runs of mass within each 3 m floor.', 'Each territory\'s area = its length × 9 m of assumed depth; its capacity at 10 m² per person.', 'The share of all territory area that sits in territories of 20 to 150 m².'],
    score: ['Estimated capacity per territory · 40 %: the average — full marks between 4 and 12 people; nothing at 0 or at 40 or more.', 'Estimated area in 20–150 m² territories · 60 %: the share of the floor area in human-scaled territories.'],
    raise: 'Subdivide long runs of mass on each floor into pieces of 20–150 m²; join the smallest crumbs.',
    lower: 'Floor-long slabs (halls) or scattered single cubes (cells).',
    cannot: 'Depth is assumed (9 m) and occupancy estimated (10 m² per person); enclosure, light and comfort are not measured.',
  },
  'Visually Connected': {
    ask: 'Can a unit look across a void at another territory — and at another level?',
    looks: 'Visually connected units see each other: across a court, a gap or a double-height void, along the floor and up or down, so the building reads as one community rather than separate corridors.',
    counts: ['From the middle of every occupied module, a straight look left, right, up and down across void or recess.', 'A <b>sightline</b> counts when it crosses 3 to 24 m of open space and ends on mass (another territory or level).', 'Modules with any sightline; modules with both a horizontal and a vertical one; sightlines per module.'],
    score: ['Modules with a sightline · 45 %: the share of occupied modules that see something.', 'Seeing another territory and another level · 30 %: the share that see both along the floor and up or down.', 'Views per module · 25 %: the average number of sightlines over 1.6.'],
    raise: 'Open the face with voids of 3 to 24 m so units face each other; run voids through several floors for vertical views.',
    lower: 'Units packed against each other with no gap, or gaps wider than 24 m with nothing across them.',
    cannot: 'Sightlines are straight lines on the face through void; glazing, railings and what is actually visible are not modelled.',
  },
  'Socially Interactive': {
    ask: 'Do the streets run past gathering pockets, so people meet on the way?',
    looks: 'Social interaction happens where circulation and shared space meet: when the route you take anyway passes an open gathering place, encounters are optional and frequent.',
    counts: ['<b>Streets</b> (floor-level recesses of 5 m or more along the face) and <b>gathering pockets</b> (recesses of 12 m² or more).', '<b>Contacts</b>: every street–pocket pair where the pocket touches the street (within a metre).', 'The share of all street length that runs within 5 m of a pocket.'],
    score: ['Street–pocket contacts · 60 %: the number of contacts over 3.', 'Street within 5 m of a pocket · 40 %: the share of street length that passes a pocket.'],
    raise: 'Give the form streets, and open the gathering pockets onto them instead of burying pockets in the mass.',
    lower: 'No street at all, or pockets and streets on different floors that never meet.',
    cannot: 'Encounters are inferred from geometry; actual use, programme and schedules are not known.',
  },
  'Village-Like': {
    ask: 'Are there clusters, streets and gathering nodes all together — like a small village?',
    looks: 'A village has three things at once: distinct groups of houses, streets that connect them, and shared centres where they meet. Missing any one of the three and it is not a village.',
    counts: ['<b>Work clusters</b>: groups of touching occupied modules.', '<b>Streets</b>: floor-level recesses of 5 m or more along the face.', '<b>Gathering nodes</b>: recesses of 12 m² or more.'],
    score: ['Work clusters · 35 %: the number of clusters over 3.', 'Streets · 30 %: the number of streets over 3.', 'Gathering nodes · 35 %: the number of pockets over 5.'],
    raise: 'Add whichever ingredient is weakest — a village needs all three.',
    lower: 'One block with no streets, or streets with nowhere to gather.',
    cannot: 'It counts the ingredients, not the quality of the neighbourhood they make.',
  },
};

export const WORDS = Object.keys(GUIDE);
